included:
  - CubeBridge
  - CubeBridgeTests

cache_path: .build/swiftlint

excluded:
  - .build
  - DerivedData
  - build

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 450
  error: 600

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 2

disabled_rules:
  - large_tuple
  - trailing_comma
